package com.kse.wmsv2.oc_cs_006.dto;

import lombok.Data;

@Data
public class OCCS006SpReExpLDto {
    /** イメージクラス名*/
    private String imageClassName;

    // 日付部
    /** 日付1 */
    private String dateyyyyMMddHHmm;
    /** 日付2 */
    private String dateyyyyMMddHHmmss;
    /** 日付3 */
    private String dateyyyyMMddHHmmss2;
    /** 日付4 */
    private String dateyyyyMMdd;

    //　ヘッダー部
    /** 輸入・輸出クラス */
    private String impExpClass;
    /** 代表統番 */
    private String taxNo;
    /** 申告種別1 */
    private String reportKindCd1;
    /** 申告種別2 */
    private String reportKindCd2;
    /** 申告種別3 */
    private String reportKindCd3;
    /** 申告種別4 */
    private String reportKindCd4;
    /** 申告種別5 */
    private String reportKindCd5;
    /** 区分 */
    private String reportClass;
    /** あて先税関 */
    private String reportDepCd;
    /** 提出先 */
    private String reportDivisionCd;
    /** 申告年月日 */
    private String reportDate;
    /** 申告番号 */
    private String reportNo;

    // ボディー部
    /** 申告条件 */
    private String reportCondition;
    /** 搬入 */
    private String carryingIn;
    /** 輸出者1 */
    private String expCustomerName1;
    /** 輸出者2 */
    private String expCustomerName2;
    /** 輸出者3 */
    private String expCustomerName3;
    /** 住所1 */
    private String expCustomerAdd1;
    /** 住所2 */
    private String expCustomerAdd2;
    /** 住所3 */
    private String expCustomerAdd3;
    /** 住所4 */
    private String expCustomerAdd4;
    /** 住所5 */
    private String expCustomerAdd5;
    /** 電話 */
    private String expCustomerTel;
    /** 税関事務管理人1 */
    private String customsOfficeJanitorName1;
    /** 税関事務管理人2 */
    private String customsOfficeJanitorName2;
    /** 税関事務管理人3 */
    private String customsOfficeJanitorName3;
    /** 税関事務管理人4 */
    private String customsOfficeJanitorName4;
    /** 税関事務管理人5 */
    private String customsOfficeJanitorName5;
    /** 税関事務管理人6 */
    private String customsOfficeJanitorName6;
    /** 仕向人1 */
    private String consigneeNo1;
    /** 仕向人2 */
    private String consigneeNo2;
    /** 仕向人3 */
    private String consigneeName;
    /** 住所1 */
    private String consigneeAdd1;
    /** 住所2 */
    private String consigneeAdd2;
    /** 住所3 */
    private String consigneeAdd3;
    /** 住所4 */
    private String consigneeAdd4;
    /** 住所5 */
    private String consigneeAdd5;
    /** 国コード */
    private String consigneeCountry;
    /** 代理人1 */
    private String agent1;
    /** 代理人2 */
    private String agent2;
    /** 通関士コード */
    private String reportCustomsSpecialistUserCd;
    /** 検査立会者 */
    private String inspectionWitness;
    /** ＡＷＢ番号先頭3桁 */
    private String awbNo1;
    /** ＡＷＢ番号 */
    private String awbNo2;
    /** 貨物個数 */
    private String carryingPiece;
    /** 保税地域1 */
    private String customsPlaceCd1;
    /** 保税地域2 */
    private String customsPlaceCd2;
    /** 蔵置税関1 */
    private String bondedWareHouseCustomsCd1;
    /** 蔵置税関2 */
    private String bondedWareHouseCustomsCd2;
    /** 最終仕向地1 */
    private String lastDestinationCd1;
    /** 最終仕向地2 */
    private String lastDestinationCd2;
    /** 事前検査済貨物等識別 */
    private String preExamCargoDisc ;
    /** 積込港1 */
    private String depPortCd1;
    /** 積込港2 */
    private String depPortCd2;
    /** 貿易形態別符号 */
    private String tradeTypeMark;
    /** 調査用符号 */
    private String customsExamMark;
    /** 出港予定年月日 */
    private String depPlaningDate;
    /** 関税 */
    private String customs ;
    /** 内国消費税 */
    private String inConsTax;
    /** その他 */
    private String other;
    /** 輸出承認証等区分 */
    private String expRecoFlg;
    /** 輸出承認証番号等(1)1 */
    private String expRecA1;
    /** 輸出承認証番号等(1)2 */
    private String expRecA2;
    /** 輸出承認証番号等(2)1 */
    private String expRecB1;
    /** 輸出承認証番号等(2)2 */
    private String expRecB2;
    /** 輸出承認証番号等(3)1 */
    private String expRecC1;
    /** 輸出承認証番号等(3)2 */
    private String expRecC2;
    /** 輸出承認証番号等(4)1 */
    private String expRecD1;
    /** 輸出承認証番号等(4)2 */
    private String expRecD2;
    /** 輸出承認証番号等(5)1 */
    private String expRecE1;
    /** 輸出承認証番号等(5)2 */
    private String expRecE2;
    /** 輸出承認証番号等(6)1 */
    private String expRecF1;
    /** 輸出承認証番号等(6)2 */
    private String expRecF2;
    /** 輸出承認証番号等(7)1 */
    private String expRecG1;
    /** 輸出承認証番号等(7)2 */
    private String expRecG2;
    /** 輸出承認証番号等(8)1 */
    private String expRecH1;
    /** 輸出承認証番号等(8)2 */
    private String expRecH2;
    /** 輸出承認証番号等(9)1 */
    private String expRecI1;
    /** 輸出承認証番号等(9)2 */
    private String expRecI2;
    /** 輸出承認証番号等(10)1 */
    private String expRecJ1;
    /** 輸出承認証番号等(10)2 */
    private String expRecJ2;
    /** 輸出承認証番号等(11)1 */
    private String expRecK1;
    /** 輸出承認証番号等(11)2 */
    private String expRecK2;
    /** 輸出承認証番号等(12)1 */
    private String expRecL1;
    /** 輸出承認証番号等(12)2 */
    private String expRecL2;
    /** 輸出承認証番号等(13)1 */
    private String expRecM1;
    /** 輸出承認証番号等(13)2 */
    private String expRecM2;
    /** 輸出承認証番号等(14)1 */
    private String expRecN1;
    /** 輸出承認証番号等(14)2 */
    private String expRecN2;
    /** 輸出承認証番号等(15)1 */
    private String expRecO1;
    /** 輸出承認証番号等(15)2 */
    private String expRecO2;
    /** 仕入書番号1 */
    private String invoiceNo1;
    /** 仕入書番号2 */
    private String invoiceNo2;
    /** 仕入書(電子） */
    private String eleInvoiceNo;
    /** 仕入書価格1 */
    private String invoiceValue1;
    /** 仕入書価格2 */
    private String invoiceValue2;
    /** 仕入書価格3 */
    private String invoiceValue3;
    /** 仕入書価格4 */
    private String invoiceValue4;
    /** ＦＯＢ価格1 */
    private String fobAmo1;
    /** ＦＯＢ価格2 */
    private String fobAmo2;
    /** 通貨レート1 */
    private String currencyRate1;
    /** 通貨レート2 */
    private String currencyRate2;
    /** 通貨レート3 */
    private String currencyRate3;
    /** 通貨レート4 */
    private String currencyRate4;
    /** ＢＰＲ合計1 */
    private String basicPriceTotal1;
    /** ＢＰＲ合計2 */
    private String basicPriceTotal2;
    /** 枚 */
    private String configure;
    /** 欄 */
    private String declareCnt;

    // フッター部
    /** 記事(税関) */
    private String news1;
    /** 記事(税関) */
    private String news2;
    /** 記事(通関) */
    private String news3;
    /** 記事(荷主) */
    private String newsShipper;
    /** 荷主セクションコード */
    private String merchantSectionCode;
    /** 荷主Ｒｅｆ Ｎｏ． */
    private String shipperReferenceNumber;
    /** 社内整理番号 */
    private String inHouseRefNumber;
    /** 利用者整理番号 */
    private String userRefNumber;
    /** 輸 出 者(入力)1 */
    private String expCustomerNameInput1;
    /** 輸 出 者(入力)2 */
    private String expCustomerNameInput2;

    // 繰返し部
    /** 欄 */
    private String reNum;
    /** 統合先欄 */
    private String mergeCd;
    /** 価格再確認 */
    private String valueCheckFlg;
    /** 品名 */
    private String item;
    /** 統計品目番号1 */
    private String itemNo1;
    /** 統計品目番号2 */
    private String itemNo2;
    /** 統計品目番号3 */
    private String itemNo3;
    /** 申告価格(FOB)1 */
    private String reportValueA;
    /** 数量（１）1 */
    private String pieceA1;
    /** 数量（１）2 */
    private String pieceA2;
    /** 申告価格(FOB)2 */
    private String reportValueB;
    /** 数量（２）1 */
    private String pieceB1;
    /** 数量（２）2 */
    private String pieceB2;
    /** ＢＰＲ按分係数 */
    private String basicPriceRate;
    /** ＢＰＲ金額1 */
    private String basicPriceAmo1;
    /** ＢＰＲ金額2 */
    private String basicPriceAmo2;
    /** 関税法70条関係(1) */
    private String taxLaw1;
    /** 関税法70条関係(2) */
    private String taxLaw2;
    /** 関税法70条関係(3) */
    private String taxLaw3;
    /** 関税法70条関係(4) */
    private String taxLaw4;
    /** 関税法70条関係(5) */
    private String taxLaw5;
    /** 輸出令別表 */
    private String otherLaw1;
    /** 外為法第48条 */
    private String otherLaw2;
    /** 減免戻税条項符号1 */
    private String otherLaw3;
    /** 減免戻税条項符号2 */
    private String otherLaw4;
    /** 減免戻税条項符号(法) */
    private String otherLaw5;
    /** 減免戻税条項符号(令) */
    private String otherLaw6;
    /** 内消税免税符号1 */
    private String inConsTaxKind1;
    /** 内消税免税符号2 */
    private String inConsTaxKind2;
    /** 内消税免税符号3 */
    private String inConsTaxKind3;

}
