package com.kse.wmsv2.oc_cs_006.dto;

import lombok.Data;

@Data
public class OCCS006ExDto {

    /** 輸入・輸出クラス */
    private String impExpClass;
    /** 日付1 */
    private String dateyyyyMMddHHmm;
    /** 日付2 */
    private String dateyyyyMMddHHmmss;
    /** 日付3 */
    private String dateyyyyMMddHHmmss2;
    /** 日付4 */
    private String dateyyyyMMdd;
    /** 申告等番号 */
    private String expReportNo;
    /** 申告区分 */
    private String esaFlg;
    /** 申告種別(大額・少額識別 + 申告等種別コード + 申告貨物識別をコード) */
    private String reportKind;
    /** 申告条件 */
    private String reportCondition;
    /** 申告者 */
    private String reportPlanPersonCd;
    /** 書類提出先1 */
    private String reportDepCd;
    /** 書類提出先2 */
    private String reportDivisionCd;
    /** 貨物番号 */
    private String cwbNo;
    /** MAWB番号 */
    private String awbNo;
    /** MAWB番号先頭3桁 */
    private String awbNo1;
    /** MAWB番号先頭3桁以外 */
    private String awbNo2;
    /** 蔵置場所1 */
    private String clearPlanPlaceCd;
    /** 蔵置場所2 */
    private String clearPlanPlaceName;
    /** 蔵置税関1 */
    private String customsPlaceName;
    /** 蔵置税関2 */
    private String customsPlaceDeptCd;
    /** 検査立会者 */
    private String customsCheckUserCd;
    /** 貨物個数 */
    private String carryingPiece;
    /** 個数単位 */
    private String unitOfPiece;
    /** 貨物重量 */
    private String carryingWeight;
    /** 重量単位 */
    private String unitOfWeight;
    /** 事故コード */
    private String troubleCd;
    /** 積載機名1 */
    private String loadingPlanFLT1;
    /** 積載機名2 */
    private String loadingPlanFLT2;
    /** 積載機名3 */
    private String loadingPlanFLT3;
    /** 品名 */
    private String item;
    /** 輸出入者1(輸出入者コード) */
    private String expCustomerNo;
    /** 輸出入者3(部門コード) */
    private String expCustomerDeptCd;
    /** 輸出入者4(輸出入者名) */
    private String expCustomerName;
    /** 税関事務管理人1 */
    private String customsOfficeJanitorCd1;
    /** 税関事務管理人2 */
    private String customsOfficeJanitorCd2;
    /** 税関事務管理人3 */
    private String customsOfficeJanitorCd3;
    /** 記事(税関用) */
    private String news1;
    /** 記事(通関業者用) */
    private String news2;
    /** ロケーション */
    private String location;
    /** 代理店 */
    private String agent;
    /** 搬入年月日 */
    private String bonWareHoCurDate;
    /** 特残貨物 */
    private String specialCargoSign;
    /** 仕向(出)地 */
    private String lastDestinationCd;
    /** 社内整理番号 */
    private String inHouseRefNumber;
    /** 審査区分+検査種別 */
    private String examinationFlgDisc;
    /** 審査区分1 */
    private String examFlg;
    /** 審査区分2 */
    private String examFlgName;
    /** 検査種別1 */
    private String examType;
    /** 検査種別2 */
    private String examTypeName;
    /** 検査実施場所1 */
    private String examPlace;
    /** 検査実施場所2 */
    private String examPlaceName;
    /** 内容 */
    private String comment;
    /** 検査方法 */
    private String examMethod;
    /** 検査方法名 */
    private String examMethodName;
    /** 全量検査表示 */
    private String allExamFlg;
    /** 再指定識別 */
    private String reSelectFlg;
    /** 検査指定日時 */
    private String examDate;
}
