package com.kse.wmsv2.oc_cs_006.dto;

import lombok.Data;

@Data
public class OCCS006SpRe2ImpDto {
    /** イメージクラス名*/
    private String imageClassName;

    // 日付部
    /** 日付1 */
    private String dateyyyyMMddHHmm;
    /** 日付2 */
    private String dateyyyyMMddHHmmss;
    /** 日付3 */
    private String dateyyyyMMddHHmmss2;
    /** 日付4 */
    private String dateyyyyMMdd;

    //　ヘッダー部
    /** 輸入・輸出クラス */
    private String impExpClass;
    /** 申告先種別 */
    private String customsKindCd;
    /** 識別符号 */
    private String discernmentMark;
    /** 区分 */
    private String reportClass;
    /** あて先税関 */
    private String reportDepCd;
    /** 提出先 */
    private String reportDivisionCd;
    /** 申告年月日 */
    private String reportDate;
    /** 申告番号 */
    private String reportNo;

    // ボディー部
    /** 申告条件 */
    private String reportCondition;
    /** 申告予定年月日 */
    private String reportPlanDate;
    /** 本申告 */
    private String declara;
    /** 輸入者1 */
    private String impCustomerName1;
    /** 輸入者2 */
    private String impCustomerName2;
    /** 輸入者3 */
    private String impCustomerName3;
    /** 住所1 */
    private String impCustomerAdd1;
    /** 住所2 */
    private String impCustomerAdd2;
    /** 住所3 */
    private String impCustomerAdd3;
    /** 住所4 */
    private String impCustomerAdd4;
    /** 住所5 */
    private String impCustomerAdd5;
    /** 住所6 */
    private String impCustomerAdd6;
    /** 電話 */
    private String impCustomerTel;
    /** 税関事務管理人1 */
    private String customsOfficeJanitorName1;
    /** 税関事務管理人2 */
    private String customsOfficeJanitorName2;
    /** 税関事務管理人3 */
    private String customsOfficeJanitorName3;
    /** 税関事務管理人4 */
    private String customsOfficeJanitorName4;
    /** 税関事務管理人5 */
    private String customsOfficeJanitorName5;
    /** 税関事務管理人6 */
    private String customsOfficeJanitorName6;
    /** 仕出人1 */
    private String expCustomerNo1;
    /** 仕出人2 */
    private String expCustomerNo2;
    /** 仕出人3 */
    private String expCustomerNo3;
    /** 住所1 */
    private String expCustomerAdd1;
    /** 住所2 */
    private String expCustomerAdd2;
    /** 住所3 */
    private String expCustomerAdd3;
    /** 住所4 */
    private String expCustomerAdd4;
    /** 住所5 */
    private String expCustomerAdd5;
    /** 住所6 */
    private String expCustomerAdd6;
    /** 国コード */
    private String expCustomerCountry;
    /** 代理人1 */
    private String agent1;
    /** 代理人2 */
    private String agent2;
    /** 通関士コード */
    private String reportCustomsSpecialistUserCd;
    /** 検査立会者 */
    private String inspectionWitness;
    /** HAWB番号先頭3桁 */
    private String cwbNo1;
    /** HAWB番号 */
    private String cwbNo2;
    /** MAWB番号先頭3桁 */
    private String awbNo1;
    /** MAWB番号 */
    private String awbNo2;
    /** 取卸港1 */
    private String portName1;
    /** 取卸港2 */
    private String portName2;
    /** 積出地1 */
    private String shipmentCd1;
    /** 積出地2 */
    private String shipmentCd2;
    /** 積載機名 */
    private String loadingPlanFlt;
    /** 入港年月日 */
    private String arrPortDate;
    /** 蔵置税関1 */
    private String bondedWareHouseCustomsCd1;
    /** 蔵置税関2 */
    private String bondedWareHouseCustomsCd2;
    /** 貨物個数 */
    private String carryingPiece;
    /** 貨物重量1 */
    private String carryingWeight;
    /** 保税地域1 */
    private String customsPlaceCd1;
    /** 保税地域2 */
    private String customsPlaceCd2;
    /** 通貨レートA1 */
    private String currencyRateA1;
    /** 通貨レートA2 */
    private String currencyRateA2;
    /** 通貨レートB1 */
    private String currencyRateB1;
    /** 通貨レートB2 */
    private String currencyRateB2;
    /** 通貨レートC1 */
    private String currencyRateC1;
    /** 通貨レートC2 */
    private String currencyRateC2;
    /** 仕入書価格1 */
    private String invoiceValue1;
    /** 仕入書価格2 */
    private String invoiceValue2;
    /** 仕入書価格3 */
    private String invoiceValue3;
    /** 仕入書価格4 */
    private String invoiceValue4;
    /** 運賃1 */
    private String fareCurrencyCd1;
    /** 運賃2 */
    private String fareCurrencyCd2;
    /** 運賃3 */
    private String fareCurrencyCd3;
    /** 保険1 */
    private String insurance1;
    /** 保険2 */
    private String insurance2;
    /** 保険3 */
    private String insurance3;


    /** 品名 */
    private String item;
    /** 申告価格1 */
    private String reportValue1;
    /** 申告価格2 */
    private String reportValue2;
    /** 原産地1 */
    private String origin1;
    /** 原産地2 */
    private String origin2;
    /** 記事 */
    private String news1;
    /** 輸入者(入力)1 */
    private String impCustomerNameInput1;
    /** 輸入者(入力)2 */
    private String impCustomerNameInput2;
    /** 社内整理番号 */
    private String inHouseRefNumber;
    /** 荷主セクションコード */
    private String merchantSectionCode;
    /** 荷主Ｒｅｆ Ｎｏ． */
    private String shipperReferenceNumber;

}
