package com.kse.wmsv2.oa_et_001.dao;

import lombok.Data;

@Data
public class OAET001FileDetailDao {
    String cwbNo;
    String awbNo;
    String bwbNo;
    String dataOrigin;
    String truckNoDate;
    String inputBassCd;
    String customsPlaceCd;
    String directionsTruckNo;
    String directionsRemarks;
    String reportNayClassCd;
    String procNo;
    String imageOutputFlg;
    String imageOutputPlace;
    String editFlg;
    String linkConnectFlg;
    String autoEsaFlg;
    String linkTruckNo;
    String origin;
    String permitClassCd;
    String currentCustomsStatusCd;
    String currentCargoStatusCd;
    String esaFlg;
    String reportCondition;
    String expReportNo;
    String largeSmallFlg;
    String reportKindCd;
    String customsKindCd1;
    String customsKindCd2;
    String reportDepCd;
    String reportDivisionCd;
    String expReportPlanDate;
    String expCustomerNo;
    String expCustomerDeptCd;
    String expCustomerOcsDeptCd;
    String expCustomerName;
    String expCustomerPostcode;
    String expCustomerAdd1;
    String expCustomerAdd2;
    String expCustomerAdd3;
    String expCustomerAdd4;
    String expCustomerAddLump;
    String expCustomerAdd;
    String expCustomerTelNo;
    String reportPlanPersonCd;
    String bondedWarehouseCd;
    String consigneeNo;
    String consigneeDeptDd;
    String consigneeOcsDeptCd;
    String consigneeName;
    String consigneeAdd1;
    String consigneeAdd2;
    String consigneeAdd3;
    String consigneeAdd4;
    String consigneeAddLump;
    String consigneeAdd;
    String consigneePostcode;
    String consigneeCountry;
    String carryingPiece;
    String carryingWeight;
    String totalPiece;
    String totalWeight;
    String linkPiece;
    String linkWeight;
    String arrivalPiece;
    String lastDestinationCd;
    String linkLastDestinationCd;
    String lastDestName;
    String depPort;
    String tradeTypeMark;
    String depPlaningDate;
    String customsExamMark;
    String expRecoFlg;
    String preExamCargoDisc;
    String expRecDisc1;
    String expRecNo1;
    String expRecDisc2;
    String expRecNo2;
    String expRecDisc3;
    String expRecNo3;
    String expRecDisc4;
    String expRecNo4;
    String expRecDisc5;
    String expRecNo5;
    String invoiceDiscernment;
    String eleIn1voiceReNo;
    String invoiceNo;
    String invoiceValConCd;
    String invoiceCurCd;
    String invoiceValue;
    String invoiceValClassCd;
    String fobCurrencyCd;
    String fobAmo;
    String linkFobAmo;
    String reportValue;
    String basicPriceTotal;
    String needLoadingRecDisc;
    String news1;
    String news2;
    String newsShipper;
    String inHouseRefNumber;
    String expStatItemNo;
    String item;
    String cargoDisc;
    String destination;
    String airline;
    String mixedForwarder;
    String agentDiv;
    String customsRequest;
    String permRecognitionNo;
    String cargoType;
    String specialCargoSign;
    String desClassDisc;
    String uldNo;
    String containerClassCd;
    String discernmentMark;
    String handringWhouseCd;
    String carringAirline;
    String expTradeContLow4;
    String incEstRePreNo;
    String correctKindCd;
    String correctReasonCd;
    String remarks;
    String otherLawCd1;
    String otherLawCd2;
    String otherLawCd3;
    String otherLawCd4;
    String otherLawCd5;
    String expTradeContCd;
    String forExchLow48;
    String customsExemptCd;
    String inconsTaxExempCd;
    String inconsTaxExempDisc;
    String origin5;
    String destination5;
    String defaultSet;
    String dummyCwbNo;
    String reportIssueDate;
    String docReportNo;
    String docClass;
    String bondInBillNo;
    String bondInBillIssueDate;
    String editGroup;
    String editGroupMakeUserCd;
    String editGroupMakeDate;
    String editDifficulty;
    String editSeverity;
    String editHold;
    String editRegUserCd;
    String editRegDate;
    String editUpdateUserCd;
    String editUpdateDate;
    String customsCheckGroupMakeDate;
    String customsCheckPriority;
    String customsCheckPriorityEdit;
    String customsCheckClass;
    String customsCheckHold;
    String customsCheckCorrect;
    String customsCheckUserCd;
    String customsCheckDate;
    String reportCustomsSpecialistUserCd;
    String edaMessageMakeFlag;
    String spsDocClassCd;
    String customsMemo;
    String flt1;
    String flt2;
    String agent;
    String bonWarehoCurDate;
    String carSlipmakeFlg;
    String fltDestination;
    String joint;
    String loadingWorker;
    String hardRecvFlag;
    String ifFareCurrencyCd;
    String ifFare;
    String ifInsuranceCurCd;
    String ifInsuranceAmount;
    String customsOfficeJanitorCd;
    String customsOfficeJanitorReNo;
    String customsOfficeJanitorName;
    String inspectionWitness;
    String shippersSecCd;
    String shippersRefNo;
    String expRecDisc6;
    String expRecDisc7;
    String expRecDisc8;
    String expRecDisc9;
    String expRecDisc10;
    String expRecDisc11;
    String expRecDisc12;
    String expRecDisc13;
    String expRecDisc14;
    String expRecDisc15;
    String expRecNo6;
    String expRecNo7;
    String expRecNo8;
    String expRecNo9;
    String expRecNo10;
    String expRecNo11;
    String expRecNo12;
    String expRecNo13;
    String expRecNo14;
    String expRecNo15;
    String conditionFlg;
    String userCd;
    String date;

    public OAET001FileDetailDao(){
        this.bwbNo = "00000000000";
        this.dataOrigin = "01";
        this.editFlg = "0";
        this.linkConnectFlg = "0";
        this.linkTruckNo = "0";
        this.currentCustomsStatusCd = "EC00600";
        this.currentCargoStatusCd = "EB00100";
        this.defaultSet = "1";
        this.docClass = "0";
        this.editHold = "0";
        this.customsCheckClass = "0";
        this.customsCheckHold = "0";
        this.customsCheckCorrect = "0";
        this.edaMessageMakeFlag = "0";
        this.spsDocClassCd = "0";
        this.hardRecvFlag = "0";
    }





}
